# svm_loss_naive and svm_loss_vectorized code implementation

In [4]:
import numpy as np

#X contains 3 images of dimension 3x4
#W contains weights for each pixel in an image of dimension 4x3
#y contains the label for each class

In [8]:
X= np.array([[56,102,161,78],[180,89,132,35],[20,147,12,174]])
print('image\n',X)
W= np.array([[.1,.8,.5,],[.4,.5,.9],[.7,.9,.3],[.2,.6,.1]])
print('weight\n',W)
y=[1,0,2]

image
 [[ 56 102 161  78]
 [180  89 132  35]
 [ 20 147  12 174]]
weight
 [[0.1 0.8 0.5]
 [0.4 0.5 0.9]
 [0.7 0.9 0.3]
 [0.2 0.6 0.1]]


# svm_loss_naive

In [6]:
# initialize the gradient as zero with the dimension of W
dW = np.zeros(W.shape) 

# compute the loss and the gradient
num_classes = W.shape[1]           #no of columns in the Weight matrix
print('num of classes\n',num_classes)
num_train = X.shape[0]             #no of images for training  
print('num of training images\n',num_train)
loss = 0.0                         


for i in range(num_train):                          #starting from i=0 upto num_train-1
    print('i=',i)
    scores = X[i].dot(W)                            #matrix multiplication of X[i] with each w 
    print('scores\n',scores)
    correct_class_score = scores[y[i]]              #correct class scorein the scores is the index value with y[i]
    print('correct_class_score\n',correct_class_score)
    loss_counter = 0
    for j in range(num_classes):                     #starting from j=0 upto num_classes-1      
        print('dW\n',dW)
        if j == y[i]:                   #if j == y[i], then skip to next value of i. ie the correct class score 
            print('j == y[',i,'], hence skipping')     #is same as the class label
            continue                                 #if j is not equal to y[i] continue
        margin = scores[j] - correct_class_score + 1 # note delta = 1# difference of scores with the correct 
                                                     #class score      
        print('margin\n',margin)                     #if margin <0, then move to the next j value
        
        if margin > 0:                               #if margin >0, then that class is contributing to the loss
            loss_counter +=1                         #loss counter updation 
            print('loss_counter\n',loss_counter)   
            loss += margin                           #margin is added to the loss, and that class is 
            print('loss added with margin\n',loss)   #contributing to loss
            dW[:,j] +=X[i]                           #the gradient is only updated when margin > 
            print('dW after X[',i,']=',X[i],' is added in js',j,'st column\n',dW)
                                                     #X[i] pixel values are added to the dW in the jth class
    
    dW[:,y[i]] +=-loss_counter*X[i]          #X[i] multiplied with loss counter and take the difference 
                                            # from the corresponding class in dW 
    print('dW after X[',i,'] multiplied with loss counter value(',loss_counter,')added with class',y[i],'\n',dW)
   
     


 
  

num of classes
 3
num of training images
 3
i= 0
scores
 [174.7 287.5 175.9]
correct_class_score
 287.5
dW
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
margin
 -111.80000000000001
dW
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
j == y[ 0 ], hence skipping
dW
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
margin
 -110.6
dW after X[ 0 ] multiplied with loss counter value( 0 )added with class 1 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
i= 1
scores
 [153.  328.3 213.2]
correct_class_score
 153.0
dW
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
j == y[ 1 ], hence skipping
dW
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
margin
 176.3
loss_counter
 1
loss added with margin
 176.3
dW after X[ 1 ]= [180  89 132  35]  is added in js 1 st column
 [[  0. 180.   0.]
 [  0.  89.   0.]
 [  0. 132.   0.]
 [  0.  35.   0.]]
dW
 [[  0. 180.   0.]
 [  0.  89.   0.]
 [  0. 132.   0.]
 [  0.  35.   0.]]
margin
 61.20000000000002
loss_counter
 2
loss added with margin
 237.500

# svm_loss_vectorized

In [7]:

loss = 0.0
dW = np.zeros(W.shape)                      # initialize the gradient as zero
print('dW\n',dW)

scores = X.dot(W)                           #score calculation
print('scores\n',scores)
correct_class_score = scores[np.arange(num_train),y] # numtrain([0,1,2]) and y=[1,0,2]
print('correct_class_score\n',correct_class_score)
margins = scores - correct_class_score[:, np.newaxis] + 1 #take the difference of all scores with 
print('margins = scores - correct_class_score\n',margins) #the correct class score
margins = np.maximum(0, margins)           #take the positive values
print('margins\n',margins)
margins[np.arange(num_train), y] = 0       #numtrain([0,1,2]) and y=[1,0,2] becomes 0, position of
print("resetting margin- correct class element to zero\n") #correct class scores
print(margins)
num_train = X.shape[0]


X_mask = np.zeros(margins.shape)         
print('X_mask\n',X_mask)
X_mask[margins>0] = 1                      #if the margin values >0, then put 1 in the corresponding position
print('dim_ofX_mask\n',X_mask.shape)
print('X_mask - margins>0\n',X_mask)

counts = np.sum(X_mask, axis=1)           #counts the class which contributes to loss
print('dim_ofcounts\n',counts.shape)
print('counts\n',counts)
X_mask[np.arange(num_train),y] = -counts  #numtrain([0,1,2]) and y=[1,0,2] where counts is subtracted
print('dim_ofX_mask\n',X_mask.shape)
print('X_mask after counts is subtracted\n',X_mask)\

dW += X.T.dot(X_mask)
print('dW after X is multiplied with X_mask \n',dW)



dW
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
scores
 [[174.7 287.5 175.9]
 [153.  328.3 213.2]
 [104.  204.7 163.3]]
correct_class_score
 [287.5 153.  163.3]
margins = scores - correct_class_score
 [[-111.8    1.  -110.6]
 [   1.   176.3   61.2]
 [ -58.3   42.4    1. ]]
margins
 [[  0.    1.    0. ]
 [  1.  176.3  61.2]
 [  0.   42.4   1. ]]
resetting margin- correct class element to zero

[[  0.    0.    0. ]
 [  0.  176.3  61.2]
 [  0.   42.4   0. ]]
X_mask
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
dim_ofX_mask
 (3, 3)
X_mask - margins>0
 [[0. 0. 0.]
 [0. 1. 1.]
 [0. 1. 0.]]
dim_ofcounts
 (3,)
counts
 [0. 2. 1.]
dim_ofX_mask
 (3, 3)
X_mask after counts is subtracted
 [[ 0. -0.  0.]
 [-2.  1.  1.]
 [ 0.  1. -1.]]
dW after X is multiplied with X_mask 
 [[-360.  200.  160.]
 [-178.  236.  -58.]
 [-264.  144.  120.]
 [ -70.  209. -139.]]
